apiVersion: v1
kind: Secret
metadata:
  name: cm-backend-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # Database configuration
  DATABASE_URL: {{ .Values.env.DATABASE_URL | b64enc }}
  DB_HOST_NAME: {{ .Values.env.DB_HOST_NAME | b64enc }}
  DB_NAME: {{ .Values.env.DB_NAME | b64enc }}
  DB_USER_NAME: {{ .Values.env.DB_USER_NAME | b64enc }}
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | b64enc }}
  DB_PORT: {{ .Values.env.DB_PORT | b64enc }}
  DB_CONNECTION_STRING: {{ .Values.env.DB_CONNECTION_STRING | b64enc }}
  
  # Celery configuration
  CELERY_BROKER_URL: {{ .Values.env.CELERY_BROKER_URL | b64enc }}
  CELERY_RESULT_BACKEND: {{ .Values.env.CELERY_RESULT_BACKEND | b64enc }}

  # Azure AD configuration
  TENANT_ID: {{ .Values.env.TENANT_ID | b64enc }}
  APP_CLIENT_ID: {{ .Values.env.APP_CLIENT_ID | b64enc }}
  OPENAPI_CLIENT_ID: {{ .Values.env.OPENAPI_CLIENT_ID | b64enc }}
  SCOPE_DESCRIPTION: {{ .Values.env.SCOPE_DESCRIPTION | b64enc }}

  # Encryption
  ENCRYPTION_KEY: {{ .Values.env.ENCRYPTION_KEY | b64enc }}

  # CubeJS configuration
  CUBEJS_DB_TYPE: {{ .Values.env.CUBEJS_DB_TYPE | b64enc }}
  CUBEJS_DB_HOST: {{ .Values.env.CUBEJS_DB_HOST | b64enc }}
  CUBEJS_DB_PORT: {{ .Values.env.CUBEJS_DB_PORT | b64enc }}
  CUBEJS_DB_NAME: {{ .Values.env.CUBEJS_DB_NAME | b64enc }}
  CUBEJS_DB_USER: {{ .Values.env.CUBEJS_DB_USER | b64enc }}
  CUBEJS_DB_PASS: {{ .Values.env.CUBEJS_DB_PASS | b64enc }}
  CUBEJS_DB_SSL: {{ .Values.env.CUBEJS_DB_SSL | b64enc }}
  CUBEJS_API_SECRET: {{ .Values.env.CUBEJS_API_SECRET | b64enc }}
  CUBEJS_DEV_MODE: {{ .Values.env.CUBEJS_DEV_MODE | b64enc }}
  CUBEJS_EXTERNAL_DEFAULT: {{ .Values.env.CUBEJS_EXTERNAL_DEFAULT | b64enc }}
  CUBEJS_SCHEDULED_REFRESH_DEFAULT: {{ .Values.env.CUBEJS_SCHEDULED_REFRESH_DEFAULT | b64enc }}
  CUBEJS_API_URL: {{ .Values.env.CUBEJS_API_URL | b64enc }}
  CUBEJS_LOG_LEVEL: {{ .Values.env.CUBEJS_LOG_LEVEL | b64enc }}
  CUBEJS_CONCURRENCY: {{ .Values.env.CUBEJS_CONCURRENCY | b64enc }}

  AZURE_OPENAI_ENDPOINT: {{ .Values.env.AZURE_OPENAI_ENDPOINT | b64enc }}
  AZURE_OPENAI_KEY: {{ .Values.env.AZURE_OPENAI_KEY | b64enc }}
  AZURE_DEPLOYMENT_NAME: {{ .Values.env.AZURE_DEPLOYMENT_NAME | b64enc }}
  AZURE_OPENAI_VERSION: {{ .Values.env.AZURE_OPENAI_VERSION | b64enc }}
